apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k82e30s0z-python
  janus-idp.io/tekton: k82e30s0z-python
  backstage.io/kubernetes-id: k82e30s0z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k82e30s0z-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
